version: '3'
services:
  app:
    container_name: slow-tunes-bot
    hostname: slowtunesbot
    build: .
    volumes:
      - data:/app/data
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    env_file:
      - ./.env
    restart: on-failure
volumes:
  data:
    name: bot-data
networks:
  default:
    name: slow-tunes-bot-network
