version: '3'
services:
  app:
    container_name: slow-tunes-bot
    hostname: slowtunesbot
    build: .
    user: 1998:1998
    volumes:
      - bot-data:/app/data
    environment:
      DEBUG: 0
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      REDIS_HOST: cache
      REDIS_PORT: 6379
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - webhook
      - cache
    networks:
      - internal
  cache:
    container_name: slow-tunes-bot-cache
    hostname: slowtunesbot-cache
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 300 1 --loglevel notice
    volumes:
      - bot-cache:/data
    networks:
      - internal
  webhook:
    container_name: slow-tunes-bot-webhook
    hostname: slowtunesbot-webhook
    image: nginx:stable-alpine
    restart: always
    user: 101:101
    ports:
      - 80:8080
    networks:
      - external
      - internal
    volumes:
      - ./webhook:/etc/nginx/templates:ro
volumes:
  bot-data:
  bot-cache:
networks:
  external:
    name: slow-tunes-bot-network
    internal: false
  internal:
    name: slow-tunes-bot-internal
    internal: true
