name: Deploy to production

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - ".*"
    branches:
      - master
  pull_request:
    types:
      - assigned
    branches:
      - master

jobs:
  pull_n_build:
    name: SSH action
    runs-on: ubuntu-latest
    steps:
      - name: Pull, build and run
        uses: appleboy/ssh-action@v0.1.8
        env:
          SHA: ${{ github.sha }}
          APP_PATH: ${{ secrets.APP_PATH }}
          DEBUG: 0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: SHA, APP_PATH, DEBUG
          script_stop: true
          script: |
            cd $APP_PATH
            git fetch
            git reset --hard $SHA
            git status
            docker-compose up -d --build
            docker system prune -f
